# Generated by Django 5.2.13 on 2026-05-15 04:18

import accounts.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otpverification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='otpverification',
            name='purpose',
            field=models.CharField(choices=[('password_reset', 'Password reset'), ('registration', 'Registration'), ('login', 'Login')], db_index=True, default='password_reset', max_length=32),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, default='', max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), accounts.validators.validate_avatar_max_size])),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('account_type', models.CharField(choices=[('property_owner', 'Property owner')], default='property_owner', max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
