# Generated by Django 5.2.13 on 2026-05-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_owner_buyer_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pending_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='purpose',
            field=models.CharField(choices=[('password_reset', 'Password reset'), ('registration', 'Registration'), ('login', 'Login'), ('email_change', 'Email change')], db_index=True, default='password_reset', max_length=32),
        ),
    ]
