# Generated by Django 5.1.5 on 2026-06-08 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_pending_owner_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
