# Generated by Django 5.1.5 on 2026-06-02 09:43

import advertisements.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0026_adminpanelimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, default='', max_length=300)),
                ('ad_type', models.CharField(choices=[('property', 'Property Ad'), ('generic', 'Generic Ad')], max_length=20)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('desktop_image', models.ImageField(blank=True, null=True, upload_to='ads/images/desktop/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), advertisements.validators.validate_ad_image_max_size])),
                ('mobile_image', models.ImageField(blank=True, null=True, upload_to='ads/images/mobile/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), advertisements.validators.validate_ad_image_max_size])),
                ('video_file', models.FileField(blank=True, null=True, upload_to='ads/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm']), advertisements.validators.validate_ad_video_max_size])),
                ('video_thumbnail', models.ImageField(blank=True, null=True, upload_to='ads/videos/thumbs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), advertisements.validators.validate_ad_image_max_size])),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='ready', max_length=12)),
                ('redirect_type', models.CharField(choices=[('property', 'Property'), ('external_url', 'External URL')], max_length=20)),
                ('external_url', models.URLField(blank=True, default='')),
                ('country', models.CharField(default='India', max_length=80)),
                ('area', models.CharField(blank=True, default='', max_length=120)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('radius_km', models.PositiveIntegerField(default=25)),
                ('placements', models.JSONField(default=list)),
                ('inject_after_every_n_properties', models.PositiveIntegerField(default=5)),
                ('max_display_per_user', models.PositiveIntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('priority', models.PositiveIntegerField(db_index=True, default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advertisements', to='properties.city')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ads', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advertisements', to='properties.district')),
                ('linked_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advertisements', to='properties.property')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advertisements', to='properties.state')),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'start_date', 'end_date'], name='advertiseme_is_acti_3c5ccf_idx'), models.Index(fields=['state', 'district', 'city'], name='advertiseme_state_i_832a0c_idx')],
            },
        ),
    ]
