# Generated by Django 5.1.5 on 2026-06-03 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
        ('properties', '0027_property_video_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='advertisements', to='properties.city'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='advertisements', to='properties.district'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='advertisements', to='properties.state'),
        ),
    ]
