# Generated by Django 5.1.5 on 2026-06-05 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0004_remove_advertisement_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True),
        ),
    ]
