# Generated by Django 5.1.5 on 2026-06-26 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0005_alter_advertisement_latitude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['priority', '-created_at']},
        ),
    ]
