# Generated by Django 5.1.5 on 2026-06-29 04:09

import advertisements.validators
import django.core.validators
from django.db import migrations, models


def migrate_pending_to_processing(apps, schema_editor):
    Advertisement = apps.get_model("advertisements", "Advertisement")
    Advertisement.objects.filter(video_processing_status="pending").update(
        video_processing_status="processing"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("advertisements", "0006_alter_advertisement_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="advertisement",
            old_name="processing_status",
            new_name="video_processing_status",
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="video_processing_status",
            field=models.CharField(
                choices=[
                    ("processing", "Processing"),
                    ("ready", "Ready"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="ready",
                max_length=12,
            ),
        ),
        migrations.RunPython(migrate_pending_to_processing, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="advertisement",
            name="video_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="ads/videos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "mp4",
                            "mov",
                            "avi",
                            "mkv",
                            "webm",
                            "m4v",
                            "3gp",
                        ]
                    ),
                    advertisements.validators.validate_ad_video_max_size,
                ],
            ),
        ),
    ]
