# Generated by Django 5.1.5 on 2025-09-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_alter_property_bathrooms_alter_property_bedrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.TextField(help_text="Price can be numeric (e.g., '1500.00') or text (e.g., 'Negotiable', 'Contact for price')"),
        ),
    ]
