from django.db import migrations, models


def _table_exists(schema_editor, table: str) -> bool:
    conn = schema_editor.connection
    with conn.cursor() as c:
        if conn.vendor == "mysql":
            c.execute(
                "SELECT COUNT(*) FROM information_schema.tables "
                "WHERE table_schema = DATABASE() AND table_name = %s",
                [table],
            )
            return c.fetchone()[0] > 0
        if conn.vendor == "sqlite":
            c.execute(
                "SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name=%s",
                [table],
            )
            return c.fetchone()[0] > 0
    return False


def create_sitesettings_if_missing(apps, schema_editor):
    """
    Create the DB table without apps.get_model('SiteSettings').

    SeparateDatabaseAndState runs RunPython with `from_state.apps`, which does not
    yet include models declared only in this block's state_operations (Django #23406
    family of behavior), so get_model('SiteSettings') raises LookupError.
    """
    if _table_exists(schema_editor, "properties_sitesettings"):
        return
    conn = schema_editor.connection
    qn = schema_editor.quote_name
    t = qn("properties_sitesettings")
    if conn.vendor == "sqlite":
        schema_editor.execute(
            f"CREATE TABLE {t} ("
            f"{qn('id')} integer NOT NULL PRIMARY KEY AUTOINCREMENT, "
            f"{qn('filter_radius')} decimal NOT NULL, "
            f"{qn('created_at')} datetime NOT NULL, "
            f"{qn('updated_at')} datetime NOT NULL)"
        )
    elif conn.vendor == "mysql":
        schema_editor.execute(
            f"CREATE TABLE {t} ("
            f"{qn('id')} bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, "
            f"{qn('filter_radius')} numeric(10, 2) NOT NULL, "
            f"{qn('created_at')} datetime(6) NOT NULL, "
            f"{qn('updated_at')} datetime(6) NOT NULL)"
        )
    elif conn.vendor == "postgresql":
        schema_editor.execute(
            f"CREATE TABLE {t} ("
            f"{qn('id')} bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "
            f"{qn('filter_radius')} numeric(10, 2) NOT NULL, "
            f"{qn('created_at')} timestamptz NOT NULL, "
            f"{qn('updated_at')} timestamptz NOT NULL)"
        )
    else:
        raise NotImplementedError(
            f"properties 0014: add CREATE TABLE for DB vendor {conn.vendor!r} "
            "or create properties_sitesettings manually."
        )


def _column_exists(schema_editor, table: str, column: str) -> bool:
    conn = schema_editor.connection
    with conn.cursor() as c:
        if conn.vendor == "mysql":
            c.execute(
                "SELECT COUNT(*) FROM information_schema.COLUMNS "
                "WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = %s AND COLUMN_NAME = %s",
                [table, column],
            )
            return c.fetchone()[0] > 0
        if conn.vendor == "sqlite":
            c.execute("PRAGMA table_info(%s)" % conn.ops.quote_name(table))
            return any(row[1] == column for row in c.fetchall())
    return False


def add_area_unit_if_missing(apps, schema_editor):
    if _column_exists(schema_editor, "properties_property", "area_unit"):
        return
    Property = apps.get_model("properties", "Property")
    # Historical Property in `from_state` does not include area_unit yet (same
    # SeparateDatabaseAndState / RunPython limitation as SiteSettings).
    field = models.CharField(
        max_length=10,
        choices=[("sqft", "Square Feet"), ("cent", "Cent")],
        default="sqft",
        help_text="Unit of measurement for area",
    )
    field.set_attributes_from_name("area_unit")
    schema_editor.add_field(Property, field)


def backfill_property_required_fields(apps, schema_editor):
    Property = apps.get_model("properties", "Property")
    Property.objects.filter(bedrooms__isnull=True).update(bedrooms=0)
    Property.objects.filter(bathrooms__isnull=True).update(bathrooms=0)
    Property.objects.filter(built_year__isnull=True).update(built_year=2000)
    Property.objects.filter(email__isnull=True).update(email="noreply@example.invalid")
    Property.objects.filter(email="").update(email="noreply@example.invalid")
    Property.objects.filter(furnishing__isnull=True).update(furnishing="Unspecified")
    Property.objects.filter(furnishing="").update(furnishing="Unspecified")
    Property.objects.filter(parking_spaces__isnull=True).update(parking_spaces=0)


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0013_ensure_property_video_column"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="SiteSettings",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        (
                            "filter_radius",
                            models.DecimalField(
                                decimal_places=2,
                                default=10.0,
                                help_text="Default filter radius in kilometers for latitude/longitude-based property searches",
                                max_digits=10,
                            ),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        "verbose_name": "Site Settings",
                        "verbose_name_plural": "Site Settings",
                    },
                ),
            ],
            database_operations=[
                migrations.RunPython(create_sitesettings_if_missing, migrations.RunPython.noop),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="property",
                    name="area_unit",
                    field=models.CharField(
                        choices=[("sqft", "Square Feet"), ("cent", "Cent")],
                        default="sqft",
                        help_text="Unit of measurement for area",
                        max_length=10,
                    ),
                    preserve_default=False,
                ),
            ],
            database_operations=[
                migrations.RunPython(add_area_unit_if_missing, migrations.RunPython.noop),
            ],
        ),
        migrations.RunPython(backfill_property_required_fields, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="property",
            name="price",
            field=models.TextField(
                help_text="Price can be numeric (e.g., '2500000') or text (e.g., '25 Lakh', 'Negotiable', 'Contact for price')"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="area",
            field=models.PositiveIntegerField(help_text="Area value"),
        ),
        migrations.AlterField(
            model_name="property",
            name="bedrooms",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="property",
            name="bathrooms",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="property",
            name="built_year",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="property",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="property",
            name="furnishing",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="property",
            name="parking_spaces",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
