# Generated by Django 5.2.12 on 2026-05-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_sitesettings_area_unit_property_non_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='area_unit',
            field=models.CharField(choices=[('sqft', 'Square Feet'), ('cent', 'Cent')], default='sqft', help_text='Unit of measurement for area', max_length=10),
        ),
    ]
