# Generated by Django 5.2.12 on 2026-05-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_property_moderation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', help_text='Public listings only show approved properties.', max_length=20),
        ),
    ]
