# Generated by Django 5.2.13 on 2026-05-15 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_property_is_featured'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='property',
            field=models.ForeignKey(blank=True, help_text='When set, enquiry is about this listing (must be approved for public POST).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='properties.property'),
        ),
        migrations.AddField(
            model_name='property',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Property owner who created this listing (non-staff).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='admin_phone',
            field=models.CharField(blank=True, default='', help_text='Platform contact phone shown on listings.', max_length=40),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='admin_whatsapp',
            field=models.CharField(blank=True, default='', help_text='Platform WhatsApp (digits or E.164) shown on listings.', max_length=40),
        ),
    ]
