# Generated by Django 5.2.13 on 2026-05-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0023_alter_propertyimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="bedrooms",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="bathrooms",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="built_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="furnishing",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
