# Generated by Django 5.2.13 on 2026-05-19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0024_property_built_fields_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertytype",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="property_types/icons/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp"]
                    )
                ],
            ),
        ),
    ]
