# Generated by Django 5.1.5 on 2026-06-02 11:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0026_adminpanelimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='property/video_thumbs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
