# Generated by Django 5.1.5 on 2026-06-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0029_alter_property_latitude_alter_property_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='mobile_app_version',
            field=models.CharField(default='1.0.0', help_text='Current published mobile app version, e.g. 1.4.3', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mobile_force_update',
            field=models.BooleanField(default=False, help_text='If true, the mobile app forces users to update.'),
        ),
    ]
