# Generated by Django 5.1.5 on 2026-06-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0030_sitesettings_mobile_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='area_cent',
            field=models.PositiveIntegerField(blank=True, help_text='Cent value when property type supports both units', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='floors',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='project_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='sighting',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='propertytype',
            name='has_area_both',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertytype',
            name='has_bathrooms',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='propertytype',
            name='has_bedrooms',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='propertytype',
            name='has_built_year',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='propertytype',
            name='has_floors',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertytype',
            name='has_parking_spaces',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='propertytype',
            name='has_project_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertytype',
            name='has_sighting',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_ownership',
            field=models.CharField(max_length=50),
        ),
    ]
