# Generated by Django 5.1.5 on 2026-06-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0032_convert_property_ownership'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertytype',
            name='has_furnishing',
            field=models.BooleanField(default=True),
        ),
    ]
