# Generated by Django 5.1.5 on 2026-06-22 07:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0034_optional_description_built_year_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.DecimalField(decimal_places=8, help_text='Area value', max_digits=18, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='area_cent',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Cent value when property type supports both units', max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
