# Generated by Django 5.1.5 on 2026-06-29 04:09

import django.core.validators
import properties.validators
from django.db import migrations, models


def set_existing_videos_ready(apps, schema_editor):
    Property = apps.get_model("properties", "Property")
    Property.objects.exclude(property_video="").filter(property_video__isnull=False).update(
        video_processing_status="ready"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0036_platform_mobile_app_versions"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="video_processing_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("processing", "Processing"),
                    ("ready", "Ready"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="ready",
                max_length=12,
                null=True,
            ),
        ),
        migrations.RunPython(set_existing_videos_ready, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="property",
            name="property_video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="property/videos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "mp4",
                            "mov",
                            "avi",
                            "mkv",
                            "webm",
                            "m4v",
                            "3gp",
                        ]
                    ),
                    properties.validators.validate_property_video_file_size,
                ],
            ),
        ),
    ]
