# Generated by Django 5.1.5 on 2026-07-01

from decimal import Decimal

from django.db import migrations, models


def _decimal_to_storage(value):
    text = format(Decimal(str(value)), "f")
    if "." in text:
        text = text.rstrip("0").rstrip(".")
    return text or "0"


def migrate_area_to_json(apps, schema_editor):
    Property = apps.get_model("properties", "Property")
    for prop in Property.objects.all().iterator():
        area_scalar = getattr(prop, "area", None)
        area_list = [_decimal_to_storage(area_scalar)] if area_scalar is not None else ["0"]
        prop.area_list = area_list
        area_decimals = [Decimal(v) for v in area_list]
        prop.area_range_min = min(area_decimals)
        prop.area_range_max = max(area_decimals)

        area_cent_scalar = getattr(prop, "area_cent", None)
        if area_cent_scalar is not None:
            cent_list = [_decimal_to_storage(area_cent_scalar)]
            prop.area_cent_list = cent_list
            cent_decimals = [Decimal(v) for v in cent_list]
            prop.area_cent_range_min = min(cent_decimals)
            prop.area_cent_range_max = max(cent_decimals)
        else:
            prop.area_cent_list = None
            prop.area_cent_range_min = None
            prop.area_cent_range_max = None

        prop.save(
            update_fields=[
                "area_list",
                "area_range_min",
                "area_range_max",
                "area_cent_list",
                "area_cent_range_min",
                "area_cent_range_max",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0037_video_processing_async"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="area_range_min",
            field=models.DecimalField(
                decimal_places=8,
                default=0,
                help_text="Minimum value in area list (for filtering)",
                max_digits=18,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="area_range_max",
            field=models.DecimalField(
                decimal_places=8,
                default=0,
                help_text="Maximum value in area list (for filtering)",
                max_digits=18,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="area_cent_range_min",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="Minimum value in area_cent list (for filtering)",
                max_digits=18,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="area_cent_range_max",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="Maximum value in area_cent list (for filtering)",
                max_digits=18,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="area_list",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="property",
            name="area_cent_list",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.RunPython(migrate_area_to_json, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="property",
            name="area",
        ),
        migrations.RemoveField(
            model_name="property",
            name="area_cent",
        ),
        migrations.RenameField(
            model_name="property",
            old_name="area_list",
            new_name="area",
        ),
        migrations.RenameField(
            model_name="property",
            old_name="area_cent_list",
            new_name="area_cent",
        ),
        migrations.AlterField(
            model_name="property",
            name="area",
            field=models.JSONField(
                default=list,
                help_text='Area values (sq.ft or cent per area_unit); e.g. ["23.56", "56.677"]',
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="area_cent",
            field=models.JSONField(
                blank=True,
                help_text='Cent values when property type supports both units; e.g. ["5.75", "2.1"]',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="area_range_min",
            field=models.DecimalField(
                db_index=True,
                decimal_places=8,
                default=0,
                help_text="Minimum value in area list (for filtering)",
                max_digits=18,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="area_range_max",
            field=models.DecimalField(
                db_index=True,
                decimal_places=8,
                default=0,
                help_text="Maximum value in area list (for filtering)",
                max_digits=18,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="area_cent_range_min",
            field=models.DecimalField(
                blank=True,
                db_index=True,
                decimal_places=8,
                help_text="Minimum value in area_cent list (for filtering)",
                max_digits=18,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="area_cent_range_max",
            field=models.DecimalField(
                blank=True,
                db_index=True,
                decimal_places=8,
                help_text="Maximum value in area_cent list (for filtering)",
                max_digits=18,
                null=True,
            ),
        ),
    ]
