# Generated by Django 5.1.5 on 2026-07-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0038_property_area_multi_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='contact_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
