# Generated by Django 5.1.5 on 2026-07-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0039_alter_property_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
