# Generated by Django 5.1.4 on 2026-07-29 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0040_alter_city_name_alter_district_name_alter_state_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='require_staff_property_approval',
            field=models.BooleanField(default=False, help_text='If true, properties created by portal staff start as pending and need admin approval. If false, staff-created properties are auto-approved.'),
        ),
    ]
