export const queryKeys = {
  properties: (params?: unknown) => ["properties", params] as const,
  property: (id: string, viewerId?: string | number | null) =>
    ["property", id, viewerId ?? "anon"] as const,
  myProperties: (params?: unknown) => ["myProperties", params] as const,
  propertyTypes: ["propertyTypes"] as const,
  features: ["features"] as const,
  locations: (params?: unknown) => ["locations", params] as const,
  testimonials: ["testimonials"] as const,
  heroBanners: ["heroBanners"] as const,
  offerBanners: ["offerBanners"] as const,
  activeAds: (placement: string, loc?: unknown) => ["activeAds", placement, loc] as const,
  siteContact: ["siteContact"] as const,
  companyContact: ["companyContact"] as const,
  siteSettings: ["siteSettings"] as const,
  mobileAppSettings: ["mobileAppSettings"] as const,
  contacts: (params?: unknown) => ["contacts", params] as const,
  owners: (params?: unknown) => ["owners", params] as const,
  adminAds: (params?: unknown) => ["adminAds", params] as const,
  states: ["states"] as const,
  districts: (stateId?: number) => ["districts", stateId] as const,
  cities: (districtId?: number) => ["cities", districtId] as const,
  adminImages: ["adminImages"] as const,
};
