# Generated by Django 5.1.6 on 2025-06-19 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_latitude_property_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='google_embedded_map_link',
            field=models.TextField(blank=True, help_text='Paste the complete iframe HTML code from Google Maps embed', null=True),
        ),
    ]
