# Generated by Django 5.2.3 on 2025-06-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='budget_range',
            field=models.CharField(blank=True, help_text="e.g., '₹50,000 - ₹1,00,000' or '$500 - $1000'", max_length=100, null=True),
        ),
    ]
