# Generated by Django 5.2.3 on 2025-06-27 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_contact_budget_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='nearby_places',
            field=models.JSONField(blank=True, help_text="List of nearby places in format: ['place1 - 1km', 'place2 - 2km']", null=True),
        ),
        migrations.DeleteModel(
            name='NearbyPlace',
        ),
    ]
