# Generated by Django 5.2.3 on 2025-06-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_alter_property_nearby_places_delete_nearbyplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='furnishing',
            field=models.CharField(max_length=50),
        ),
    ]
