name: Deploy Backend

on:
  push:
    branches:
      - master
    paths:
      - 'Backend/**'
      - '.github/workflows/backend-deploy.yml'

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Backend to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e

            echo "Moving to project..."
            cd ~/Property-Buylands

            echo "Pulling latest code..."
            git pull origin master

            echo "Entering Backend..."
            cd Backend

            echo "Activating Virtual Environment..."
            source venv/bin/activate

            echo "Installing dependencies..."
            pip install -r requirements.txt

            echo "Running migrations..."
            python manage.py migrate --noinput

            echo "Collecting static files..."
            python manage.py collectstatic --noinput

            echo "Checking Django..."
            python manage.py check

            echo "Reloading systemd..."
            sudo systemctl daemon-reload

            echo "Restarting services..."
            sudo systemctl restart buylands
            sudo systemctl restart nginx

            echo "Deployment completed successfully."
